### ISSUE TITLE
Clean up article "app tracking transperancy"

### ISSUE THREAD

**Issue by voidedmain** [TelemetryDeck/docs#90]
- [x] Link at the bottom still says "TelemetryDeck Beta"
- [x] text specifically mentions indie devs -> needs to be more generic
- [x] other minor things that need to be fixed

Link: https://telemetrydeck.com/docs/articles/app-tracking-transparency/
